# -*- coding: utf-8 -*-
$:.unshift("../../lib")
require 'motion/project'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TestSuite'
  app.deployment_target = ENV['deployment_target'] if ENV['deployment_target']
end
