# -*- coding: utf-8 -*-
$:.unshift("../../lib")
require 'motion/project/template/android'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TestAndroid'
  app.api_version = '18'
  app.sdk_path = File.expand_path('~/src/android-sdk-macosx')
  app.ndk_path = File.expand_path('~/src/android-ndk-r9d')

  # Make sure the main file is compiled and executed first.
  ary = app.files
  ary.delete('./app/main.rb')
  if files = ENV['files']
    files = files.split(',')
    ary.delete_if do |path|
      base = File.basename(path)
      !files.any? { |x| base.include?(x) }
    end
  end
  ary.unshift('./app/main.rb')
end
