$:.unshift('../../lib')
require 'rubixir/rake'

Motion::App.setup do |app|
  app.name = 'mapview'
  app.frameworks << 'CoreLocation'
  app.frameworks << 'MapKit'
  app.frameworks << 'AddressBook'
end
