$:.unshift('../../lib')
require 'motion/rake'

Motion::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'MapView'
  app.frameworks << 'CoreLocation'
  app.frameworks << 'MapKit'
  app.frameworks << 'AddressBook'
end
