$:.unshift("../../lib")
require 'motion/project/template/ios'
# require 'motion/project/template/osx'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'TestTime'
end
