# -*- coding: utf-8 -*-
$:.unshift(File.expand_path('../../../lib', __FILE__))
require 'motion/project/template/ios'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'MacBacon UI'
  app.sdk_version = '6.1'
  app.frameworks << 'CoreGraphics'
end
