# -*- coding: utf-8 -*-
$:.unshift("../../lib")
require 'motion/project/template/android'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'WebViewDemo'
  app.api_version = 'L' 
end
